import random
import datetime

WORD_LIST: tuple = (
    "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult",
    "after", "again", "agent", "agree", "ahead", "alarm", "album", "alert",
    "alien", "align", "alike", "alive", "alley", "allow", "alone", "along",
    "aloud", "alter", "angel", "anger", "angle", "angry", "anime", "ankle",
    "annex", "antic", "anvil", "apart", "apple", "apply", "apron", "argue",
    "arise", "armor", "aroma", "arose", "array", "arrow", "asset", "attic",
    "audio", "audit", "avoid", "awake", "award", "aware", "awful", "awoke",
    "basic", "basis", "batch", "beach", "beard", "beast", "begin", "being",
    "below", "bench", "berry", "bevel", "black", "blade", "blame", "bland",
    "blank", "blare", "blast", "blaze", "bleed", "blend", "bless", "blind",
    "blink", "bloat", "block", "blood", "bloom", "blown", "blues", "blunt",
    "blurt", "board", "boast", "bonus", "boost", "booth", "bound", "boxer",
    "brace", "braid", "brain", "brand", "brave", "bravo", "bread", "break",
    "breed", "brick", "bride", "brief", "brine", "bring", "brink", "brisk",
    "broad", "broke", "brook", "broom", "brown", "brush", "budge", "build",
    "built", "bulge", "bunch", "burst", "buyer", "bylaw",
    "cabin", "camel", "candy", "cargo", "carry", "carve", "catch", "cause",
    "cease", "chain", "chair", "chalk", "chaos", "charm", "chart", "chase",
    "cheap", "check", "cheek", "cheer", "chess", "chest", "chief", "child",
    "chill", "chimp", "choir", "chord", "chunk", "civic", "civil", "claim",
    "clamp", "clang", "clash", "clasp", "class", "clean", "clear", "click",
    "cliff", "climb", "cling", "cloak", "clock", "clone", "close", "cloth",
    "cloud", "clown", "cluck", "clump", "coach", "coast", "cobra", "comet",
    "comic", "coral", "count", "court", "cover", "covet", "crack",
    "craft", "crake", "crane", "crash", "creak", "cream", "creek", "creep", "crest",
    "crime", "crisp", "cross", "crowd", "crown", "crust", "crush", "crypt",
    "curve", "cycle",
    "daily", "dairy", "dance", "datum", "dealt", "debut", "decal", "decay",
    "decoy", "deeds", "delta", "dense", "depth", "derby", "devil", "digit",
    "dirty", "disco", "ditch", "divert", "dizzy", "dodge", "doing", "donor",
    "doubt", "dough", "draft", "drain", "drama", "drape", "drawl", "drawn",
    "dread", "dream", "dress", "drift", "drink", "drive", "droit", "drone",
    "drove", "drunk", "dryer", "duchy", "dully", "dunce", "dwell", "dwelt",
    "dying",
    "eager", "eagle", "early", "earth", "eaten", "eight", "elite", "email",
    "ember", "empty", "enemy", "enjoy", "enter", "entry", "equal", "error",
    "essay", "event", "every", "exact", "extra",
    "fable", "facet", "fairy", "faith", "false", "fancy", "fatal", "fault",
    "feast", "fence", "feral", "ferry", "fever", "fiber", "field", "fiery",
    "fifth", "fifty", "fight", "final", "finch", "first", "fixed", "flake",
    "flame", "flank", "flare", "flash", "flask", "flair", "fleet", "flesh",
    "flick", "fling", "flint", "float", "flock", "flood", "floor", "flour",
    "flown", "fluff", "fluke", "flunk", "flush", "foamy", "focus", "force",
    "forge", "forth", "forum", "found", "frame", "frank", "fraud", "fresh",
    "front", "frost", "froze", "fruit", "fully", "fungi", "funky", "funny",
    "fuzzy",
    "gauge", "gecko", "ghost", "giddy", "given", "gland", "glare", "glass",
    "gleam", "glide", "gloom", "gloss", "glove", "glowing", "gnash", "gnome",
    "gorge", "gouge", "grace", "grade", "grand", "grant", "grasp", "grass",
    "grate", "grave", "graze", "greed", "greet", "grief", "grill", "grind",
    "groan", "groin", "grope", "gross", "group", "grove", "growl", "grown",
    "gruel", "gruff", "guard", "guile", "guise", "gusto", "gypsy",
    "habit", "harsh", "haste", "haven", "havoc", "heart", "heavy", "hedge",
    "heist", "hello", "herbs", "heron", "hinge", "hippo", "hitch", "hoard", "hobby",
    "holly", "honey", "honor", "horse", "hotel", "hound", "house",
    "human", "humor", "hurry", "hyena",
    "ideal", "idiom", "idiot", "igloo", "image", "imply", "inept", "infer",
    "inner", "input", "irony", "issue", "ivory",
    "jaunt", "jewel", "joust", "judge", "juice", "juicy", "jumbo", "jumpy",
    "kayak", "knack", "kneel", "knife", "knock", "knoll", "known",
    "label", "lance", "large", "laser", "later", "laugh", "layer", "leaky",
    "learn", "least", "leave", "legal", "lemon", "level", "light", "lilac",
    "limit", "linen", "liner", "liver", "llama", "lobby", "local", "lodge",
    "logic", "lonely", "loose", "lower", "loyal", "lucid", "lucky", "lumpy",
    "lunar", "lunch", "lusty",
    "magic", "major", "maker", "manor", "maple", "march", "marry", "match",
    "matte", "mayor", "media", "mercy", "merit", "merry", "metal", "might",
    "minor", "minus", "mixed", "model", "moist", "money", "month", "moral",
    "mossy", "motel", "motto", "mount", "mourn", "mouse", "mouth", "mural",
    "music", "musky", "musty", "myrrh", "mystery",
    "naive", "nasal", "naval", "never", "night", "noble", "noise", "north",
    "notch", "noted", "novel", "nurse", "nymph",
    "occur", "offer", "often", "olive", "onset", "optic", "order", "other",
    "ought", "outdo", "outer", "outrun", "ozone",
    "paint", "panic", "paper", "party", "pasta", "patch", "pause", "peace",
    "peach", "pearl", "pedal", "penny", "perch", "peril", "phase", "phone",
    "photo", "piano", "piece", "pilot", "pinch", "pixel", "pizza", "place",
    "plaid", "plain", "plank", "plant", "plate", "plaza", "plead", "pluck",
    "plumb", "plume", "plump", "plunk", "point", "poker", "polar", "polka",
    "poppy", "pound", "power", "prank", "press", "price", "pride", "prime",
    "print", "prior", "prism", "prize", "probe", "prone", "proof", "prose",
    "proud", "prowl", "prune", "psalm", "pulse", "punch", "puppy", "purge",
    "queen", "query", "quest", "queue", "quick", "quiet", "quirk", "quota",
    "quote",
    "rabbi", "radar", "radio", "raise", "rally", "ranch", "rapid", "raven",
    "reach", "ready", "realm", "rebel", "refer", "reign", "relax", "relic",
    "remix", "repay", "repel", "resin", "retro", "revel", "rider", "ridge",
    "risky", "rival", "river", "rivet", "robin", "robot", "rocky", "rouge",
    "rough", "round", "route", "royal", "rugby", "ruler", "rusty",
    "saint", "salad", "sauce", "scale", "scalp", "scant", "scare", "scarf",
    "scary", "scene", "scone", "score", "scout", "scowl", "scram", "scrap",
    "scrawl", "screw", "scrub", "seize", "sense", "serum", "setup", "seven",
    "shade", "shake", "shaky", "shall", "shame", "shape", "share", "shark",
    "sharp", "shawl", "sheen", "sheep", "sheer", "shelf", "shell", "shift",
    "shine", "shirt", "shock", "shore", "short", "shout", "shove", "shown",
    "siege", "sight", "silky", "silly", "since", "sixth", "sixty", "sized",
    "skill", "skulk", "skull", "skunk", "slate", "sleet", "slick", "slide",
    "slime", "sling", "sloth", "slump", "slunk", "slurp", "smart", "smash",
    "smell", "smile", "smirk", "smite", "smock", "smoke", "snack", "snail",
    "snake", "snare", "sneak", "sneer", "snide", "sniff", "snore", "snowy",
    "solar", "solid", "solve", "sorry", "south", "space", "spare", "spark",
    "speak", "spear", "speed", "spend", "spice", "spill", "spine", "spite",
    "spook", "spoon", "sport", "spout", "spray", "spree", "sprig", "squad",
    "squab", "squat", "squid", "stack", "stage", "stain", "stair", "stake",
    "stale", "stalk", "stand", "stare", "stark", "start", "state", "stays",
    "steak", "steal", "steam", "steel", "steep", "steer", "stern", "stick",
    "stiff", "still", "stock", "stomp", "stone", "stood", "storm", "story",
    "stout", "stove", "strap", "straw", "stray", "strip", "strobe", "strum",
    "study", "stunt", "style", "sugar", "suite", "super", "surge", "swamp",
    "swear", "sweat", "sweep", "sweet", "swift", "swipe", "swirl", "sword",
    "swore", "sworn", "syrup",
    "table", "taper", "taste", "taunt", "tease", "tepid", "theft", "their",
    "theme", "there", "thick", "thing", "think", "third", "thorn", "those",
    "three", "threw", "throw", "thumb", "tiara", "tiger", "tighten", "tipsy",
    "titan", "toast", "token", "tonic", "torch", "total", "touch", "tough",
    "towel", "toxic", "trace", "track", "trade", "trail", "train", "trait",
    "trash", "trawl", "treat", "trend", "trick", "trill", "trite", "troop",
    "trove", "truce", "truck", "truly", "trump", "trunk", "trust", "truth",
    "tulip", "tumor", "tuner", "tunic", "tuple", "tweed", "twice", "twirl",
    "tying",
    "ulcer", "ultra", "unify", "union", "unite", "unity", "until", "upper",
    "upset", "urban", "usage", "usher", "utter",
    "valid", "value", "valve", "vapor", "vault", "venom", "venue", "verge",
    "verse", "vicar", "video", "vigor", "viral", "virus", "visor", "vital",
    "vivid", "vocal", "voice", "voila", "vomit", "voter",
    "wager", "waltz", "waste", "watch", "water", "weary", "weave", "wedge",
    "weedy", "weigh", "weird", "whale", "wheat", "wheel", "where", "which",
    "while", "whiff", "whirl", "white", "whole", "whose", "widen", "widow",
    "witch", "women", "world", "worry", "worse", "worst", "worth", "wound",
    "wrath", "wrist", "wrote",
    "yacht", "yearn", "yield", "young", "yours", "youth",
    "zesty", "zilch", "zippy", "zombie", "zonal",
)

# Filter to only valid 5-letter words
WORD_LIST = tuple(w for w in WORD_LIST if len(w) == 5)

VALID_GUESSES: set = set(WORD_LIST)

_EPOCH = datetime.date(2025, 1, 1)


def get_daily_word() -> str:
    delta = (datetime.date.today() - _EPOCH).days
    return WORD_LIST[delta % len(WORD_LIST)]


def get_random_word() -> str:
    return random.choice(WORD_LIST)


def is_valid_guess(word: str) -> bool:
    return word.lower() in VALID_GUESSES
